<?php

if ( function_exists( 'lazyblocks' ) ) :

    // Fiche produit
    lazyblocks()->add_block( array(
        'id' => 2084,
        'title' => 'Pharmacie - Fiche produit',
        'icon' => 'dashicons dashicons-clipboard',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/fiche-produit',
        'description' => '',
        'category' => 'pharmacie',
        'category_label' => 'Pharmacie',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_16a9294ad0' => array(
                'sort' => '1',
                'child_of' => '',
                'label' => 'Indication',
                'name' => 'indication',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'true',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_155a334ff1' => array(
                'sort' => '2',
                'child_of' => '',
                'label' => 'Composition',
                'name' => 'composition',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'true',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_eaab8645ec' => array(
                'sort' => '3',
                'child_of' => '',
                'label' => 'Mode d\'action',
                'name' => 'action',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'true',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_ac5a0a4c4b' => array(
                'sort' => '4',
                'child_of' => '',
                'label' => 'Utilisation',
                'name' => 'utilisation',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'true',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_245b4a4e76' => array(
                'sort' => '5',
                'child_of' => '',
                'label' => 'Conseils',
                'name' => 'conseils',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'true',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_30ebb34f15' => array(
                'sort' => '6',
                'child_of' => '',
                'label' => 'Plus produit',
                'name' => 'avantages',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'true',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_a48b584997' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Précautions',
                'name' => 'precautions',
                'type' => 'inner_blocks',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '',
            'editor_css' => '',
            'frontend_html' => 'Render frontend produit !',
            'frontend_css' => '',
        ),
        'condition' => array(
            0 => 'produit',
        ),
    ) );

    // Plus/Moins
    lazyblocks()->add_block( array(
        'id' => 2065,
        'title' => 'Plus/Moins',
        'icon' => 'dashicons dashicons-plus',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/plus-moins',
        'description' => '',
        'category' => 'common',
        'category_label' => 'common',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_6b49994efd' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Plus',
                'name' => 'plus',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_697b9b479a' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Moins',
                'name' => 'moins',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '',
            'editor_css' => '',
            'frontend_html' => 'Render +- !!',
            'frontend_css' => '',
        ),
        'condition' => array(
        ),
    ) );

    // Formules HE
    lazyblocks()->add_block( array(
        'id' => 1680,
        'title' => 'Formules d\'HE',
        'icon' => 'dashicons dashicons-lightbulb',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/formules-he',
        'description' => '',
        'category' => 'pharmacie',
        'category_label' => 'Pharmacie',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_2bf82c4a77' => array(
                'sort' => '1',
                'child_of' => '',
                'label' => 'Titre',
                'name' => 'titre',
                'type' => 'text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_adaa144b26' => array(
                'sort' => '2',
                'child_of' => '',
                'label' => 'Ingrédients',
                'name' => 'ingredients',
                'type' => 'repeater',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_b4694146be' => array(
                'sort' => '3',
                'child_of' => 'control_adaa144b26',
                'label' => 'Quantité',
                'name' => 'quantite',
                'type' => 'text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_f9c87343bd' => array(
                'sort' => '4',
                'child_of' => 'control_adaa144b26',
                'label' => 'Ingrédient',
                'name' => 'ingredient',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_3fc8454bc5' => array(
                'sort' => '5',
                'child_of' => '',
                'label' => 'Instructions',
                'name' => 'instructions',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_6adad14847' => array(
                'sort' => '6',
                'child_of' => '',
                'label' => 'Source',
                'name' => 'source',
                'type' => 'url',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '',
            'editor_css' => '',
            'frontend_html' => 'Render formules HE !!',
            'frontend_css' => '',
        ),
        'condition' => array(
            0 => 'aromatherapie',
        ),
    ) );

    // Conseils
    lazyblocks()->add_block( array(
        'id' => 1098,
        'title' => 'Conseils',
        'icon' => 'dashicons dashicons-format-status',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/conseils',
        'description' => '',
        'category' => 'pharmacie',
        'category_label' => 'Pharmacie',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_331a064cf4' => array(
                'sort' => '1',
                'child_of' => '',
                'label' => 'Titre',
                'name' => 'titre',
                'type' => 'text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_3ee9bb41e6' => array(
                'sort' => '2',
                'child_of' => '',
                'label' => 'Conseil',
                'name' => 'conseil',
                'type' => 'rich_text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_2f5a2440ef' => array(
                'sort' => '3',
                'child_of' => '',
                'label' => 'Source',
                'name' => 'source',
                'type' => 'url',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '',
            'editor_css' => '',
            'frontend_html' => 'Render conseils !!',
            'frontend_css' => '',
        ),
        'condition' => array(
            0 => 'aromatherapie',
        ),
    ) );

    // Précautions
    lazyblocks()->add_block( array(
        'id' => 1096,
        'title' => 'Précautions',
        'icon' => 'dashicons dashicons-warning',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/precautions',
        'description' => '',
        'category' => 'pharmacie',
        'category_label' => 'Pharmacie',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_d13aa24fd9' => array(
                'sort' => '1',
                'child_of' => '',
                'label' => 'Précaution',
                'name' => 'precaution',
                'type' => 'repeater',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_62693848dc' => array(
                'sort' => '2',
                'child_of' => 'control_d13aa24fd9',
                'label' => 'Niveau',
                'name' => 'precaution_status',
                'type' => 'select',
                'choices' => array(
                    array(
                        'value' => '0',
                        'label' => 'N/A',
                    ),
                    array(
                        'value' => '1',
                        'label' => 'PE',
                    ),
                    array(
                        'value' => '2',
                        'label' => 'CI',
                    ),
                ),
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_cc1bd649e8' => array(
                'sort' => '3',
                'child_of' => 'control_d13aa24fd9',
                'label' => 'Commentaire',
                'name' => 'precaution_commentaire',
                'type' => 'textarea',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_364a9d4c0f' => array(
                'sort' => '4',
                'child_of' => '',
                'label' => 'Âge minimal',
                'name' => 'age_minimal',
                'type' => 'number',
                'min' => '0',
                'max' => '100',
                'step' => '1',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_819a7940d3' => array(
                'sort' => '5',
                'child_of' => '',
                'label' => 'OK Femme enceinte',
                'name' => 'femme_enceinte_ok',
                'type' => 'toggle',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_9658a14486' => array(
                'sort' => '6',
                'child_of' => '',
                'label' => 'OK Femme allaitante',
                'name' => 'femme_allaitante_ok',
                'type' => 'toggle',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '',
            'editor_css' => '',
            'frontend_html' => 'Render precautions !!',
            'frontend_css' => '',
        ),
        'condition' => array(
            0 => 'post',
            1 => 'aromatherapie',
            2 => 'produit',
        ),
    ) );

    // Utilisation HE
    lazyblocks()->add_block( array(
        'id' => 1085,
        'title' => 'Utilisation des HE',
        'icon' => 'dashicons dashicons-forms',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/utilisation-he',
        'description' => '',
        'category' => 'pharmacie',
        'category_label' => 'Pharmacie',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_572b604a4c' => array(
                'sort' => '1',
                'child_of' => '',
                'label' => 'Ambiance olfactive',
                'name' => 'ambiance_recos',
                'type' => 'select',
                'choices' => array(
                    array(
                        'value' => '0',
                        'label' => 'N/A',
                    ),
                    array(
                        'value' => '1',
                        'label' => '*',
                    ),
                    array(
                        'value' => '2',
                        'label' => '**',
                    ),
                    array(
                        'value' => '3',
                        'label' => '***',
                    ),
                    array(
                        'value' => '-1',
                        'label' => 'CI',
                    ),
                ),
                'min' => '0',
                'max' => '3',
                'step' => '1',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '0',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_afbbce447a' => array(
                'sort' => '2',
                'child_of' => '',
                'label' => 'Commentaire ambiance olfactive',
                'name' => 'ambiance_commentaire',
                'type' => 'textarea',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_5dcb4c4d59' => array(
                'sort' => '3',
                'child_of' => '',
                'label' => 'Diffusion',
                'name' => 'diffusion_recos',
                'type' => 'select',
                'choices' => array(
                    array(
                        'value' => '0',
                        'label' => 'N/A',
                    ),
                    array(
                        'value' => '1',
                        'label' => '*',
                    ),
                    array(
                        'value' => '2',
                        'label' => '**',
                    ),
                    array(
                        'value' => '3',
                        'label' => '***',
                    ),
                    array(
                        'value' => '-1',
                        'label' => 'CI',
                    ),
                ),
                'min' => '0',
                'max' => '3',
                'step' => '1',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '0',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_bbea76421d' => array(
                'sort' => '4',
                'child_of' => '',
                'label' => 'Commentaire diffusion',
                'name' => 'diffusion_commentaire',
                'type' => 'textarea',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_e989c04a8c' => array(
                'sort' => '5',
                'child_of' => '',
                'label' => 'Application',
                'name' => 'application_recos',
                'type' => 'select',
                'choices' => array(
                    array(
                        'value' => '0',
                        'label' => 'N/A',
                    ),
                    array(
                        'value' => '1',
                        'label' => '*',
                    ),
                    array(
                        'value' => '2',
                        'label' => '**',
                    ),
                    array(
                        'value' => '3',
                        'label' => '***',
                    ),
                    array(
                        'value' => '-1',
                        'label' => 'CI',
                    ),
                ),
                'min' => '0',
                'max' => '3',
                'step' => '1',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '0',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_04a83e4b5e' => array(
                'sort' => '6',
                'child_of' => '',
                'label' => 'Commentaire application',
                'name' => 'application_commentaire',
                'type' => 'textarea',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_3dfadd4743' => array(
                'sort' => '7',
                'child_of' => '',
                'label' => 'Voie orale',
                'name' => 'orale_recos',
                'type' => 'select',
                'choices' => array(
                    array(
                        'value' => '0',
                        'label' => 'N/A',
                    ),
                    array(
                        'value' => '1',
                        'label' => '*',
                    ),
                    array(
                        'value' => '2',
                        'label' => '**',
                    ),
                    array(
                        'value' => '3',
                        'label' => '***',
                    ),
                    array(
                        'value' => '-1',
                        'label' => 'CI',
                    ),
                ),
                'min' => '0',
                'max' => '3',
                'step' => '1',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '0',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_b8e9d44a35' => array(
                'sort' => '8',
                'child_of' => '',
                'label' => 'Commentaire voie orale',
                'name' => 'orale_commentaire',
                'type' => 'textarea',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_cce9c84a96' => array(
                'sort' => '9',
                'child_of' => '',
                'label' => 'Inhalation sèche',
                'name' => 'inhalation_seche_recos',
                'type' => 'select',
                'choices' => array(
                    array(
                        'value' => '0',
                        'label' => 'N/A',
                    ),
                    array(
                        'value' => '1',
                        'label' => '*',
                    ),
                    array(
                        'value' => '2',
                        'label' => '**',
                    ),
                    array(
                        'value' => '3',
                        'label' => '***',
                    ),
                    array(
                        'value' => '-1',
                        'label' => 'CI',
                    ),
                ),
                'min' => '0',
                'max' => '3',
                'step' => '1',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '0',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_5f583a401a' => array(
                'sort' => '10',
                'child_of' => '',
                'label' => 'Commentaire inhalation sèche',
                'name' => 'inhalation_seche_commentaire',
                'type' => 'textarea',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_7d1b90416c' => array(
                'sort' => '11',
                'child_of' => '',
                'label' => 'Inhalation humide',
                'name' => 'inhalation_humide_recos',
                'type' => 'select',
                'choices' => array(
                    array(
                        'value' => '0',
                        'label' => 'N/A',
                    ),
                    array(
                        'value' => '1',
                        'label' => '*',
                    ),
                    array(
                        'value' => '2',
                        'label' => '**',
                    ),
                    array(
                        'value' => '3',
                        'label' => '***',
                    ),
                    array(
                        'value' => '-1',
                        'label' => 'CI',
                    ),
                ),
                'min' => '0',
                'max' => '3',
                'step' => '1',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '0',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_7bf90c4a33' => array(
                'sort' => '12',
                'child_of' => '',
                'label' => 'Commentaire inhalation humide',
                'name' => 'inhalation_humide_commentaire',
                'type' => 'textarea',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_2ddac74870' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Sauna facial',
                'name' => 'sauna_facial_recos',
                'type' => 'select',
                'choices' => array(
                    array(
                        'value' => '0',
                        'label' => 'N/A',
                    ),
                    array(
                        'value' => '1',
                        'label' => '*',
                    ),
                    array(
                        'value' => '2',
                        'label' => '**',
                    ),
                    array(
                        'value' => '3',
                        'label' => '***',
                    ),
                    array(
                        'value' => '-1',
                        'label' => 'CI',
                    ),
                ),
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '0',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_3ea9314a7a' => array(
                'sort' => '',
                'child_of' => '',
                'label' => 'Commentaire sauna facial',
                'name' => 'sauna_facial_commentaire',
                'type' => 'textarea',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '',
            'editor_css' => '',
            'frontend_html' => 'Render utilisation HE !!',
            'frontend_css' => '',
        ),
        'condition' => array(
            0 => 'aromatherapie',
        ),
    ) );

    // Identité
    lazyblocks()->add_block( array(
        'id' => 32,
        'title' => 'Identité',
        'icon' => 'dashicons dashicons-info',
        'keywords' => array(
        ),
        'slug' => 'lazyblock/identite',
        'description' => '',
        'category' => 'pharmacie',
        'category_label' => 'Pharmacie',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => true,
            'inserter' => true,
        ),
        'controls' => array(
            'control_233839423f' => array(
                'sort' => '2',
                'child_of' => '',
                'label' => 'Nom latin',
                'name' => 'nom_latin',
                'type' => 'text',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_ea4b0940e1' => array(
                'sort' => '4',
                'child_of' => '',
                'label' => 'Composition',
                'name' => 'composition',
                'type' => 'repeater',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'content',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_c448a344f5' => array(
                'sort' => '5',
                'child_of' => 'control_ea4b0940e1',
                'label' => 'Pourcentage',
                'name' => 'pourcentage',
                'type' => 'number',
                'min' => '0',
                'max' => '100',
                'step' => '1',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
            'control_ed193b4923' => array(
                'sort' => '6',
                'child_of' => 'control_ea4b0940e1',
                'label' => 'Molécule',
                'name' => 'molecule',
                'type' => 'url',
                'min' => '',
                'max' => '',
                'step' => '',
                'date_time_picker' => 'date_time',
                'multiline' => 'false',
                'default' => '',
                'checked' => 'false',
                'placement' => 'inspector',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
            ),
        ),
        'code' => array(
            'editor_html' => '',
            'editor_css' => '',
            'frontend_html' => 'Render identité HE !!',
            'frontend_css' => '',
        ),
        'condition' => array(
            0 => 'aromatherapie',
        ),
    ) );

endif;
